### ISSUE TITLE
大佬，todo list什么时候做？好像下载下来的好像不是一般的视频格式（flv、mp4......）？

### ISSUE THREAD

**Issue by linsamasama** [MunMunMiao/BilibiliVideoDownload#1]

**Comment by MunMunMiao** [comment]
最近迷上了go，估计会用go重写这些功能和todo list。
因为我看到编码格式有h264、h265等等的格式，避免封装容器可能不兼容某些编码格式，索性直接用万能的mkv了。

**Comment by linsamasama** [comment]
> 最近迷上了go，估计会用go重写这些功能和todo list。（探索中，加上最近忙）
> 因为我看到编码格式有h264、h265等等的格式，避免封装容器可能不兼容某些编码格式，索性直接用万能的mkv了。

没怎么看你代码就提了这个issue，我直接修改输出格式就可以了。
然后基于你的代码手拙改了一下增加批量下载某up的所有视频和封面。
大佬牛逼

**Comment by MunMunMiao** [comment]
哔哩哔哩 (゜-゜)つロ 干杯~
