### ISSUE TITLE
Can't run by "npx bilibili-cli -b BV1k4411e7Va" on raspi shell

### ISSUE THREAD

**Issue by shotetet** [MunMunMiao/BilibiliVideoDownload#6]
Can't run by "npx bilibili-cli -b BV1k4411e7Va" or "npx bilibili-cli -h" on raspberrypi OS shell

```
@raspberrypi:~/ $ npx bilibili-cli -b BV1k4411e7Va
npx: installed 31 in 61.472s
Unexpected token ?
@raspberrypi:~/ $ npx bilibili-cli
npx: installed 31 in 57.456s
Unexpected token ?
```

Is there any new package need to be install?

**Comment by MunMunMiao** [comment]
please tell me your OS, node and npm version. maybe you can try ```npx bilibili-cli@latest``` getting new version

**Comment by shotetet** [comment]
Hi, my OS, node and npm version show as bellow.
```
@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux
@raspberrypi:~ $ npm -v
5.8.0
@raspberrypi:~ $ node -v
v10.24.0
@raspberrypi:~ $ npx bilibili-cli@latest
npx: installed 31 in 50.948s
Unexpected token ?
```
I tried to update npm version after, but it crashed after update by `npm install npm@latest -g`.
I will reinstall the npm and tried to upgrade it again.
Thanks!!

**Comment by MunMunMiao** [comment]
node version need >=18.0.0. Sorry, I didn't explain clearly.

**Comment by shotetet** [comment]
After update node to the latest version it execute successfully.
Thanks for help!!
